# Generated by Django 4.1.8 on 2023-05-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acidentes_RR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_acidente', models.IntegerField()),
                ('data_acidente', models.DateField()),
                ('dia_semana', models.TextField(max_length=255)),
                ('fase_dia', models.TextField(max_length=255)),
                ('tp_acidente', models.TextField(max_length=255)),
                ('cond_meteorologica', models.TextField(max_length=255)),
                ('end_acidente', models.TextField(max_length=255)),
                ('num_end_acidente', models.IntegerField()),
                ('cep_acidente', models.IntegerField()),
                ('bairro_acidente', models.TextField(max_length=255)),
                ('km_via_acidente', models.IntegerField()),
                ('latitude_acidente', models.TextField(max_length=255)),
                ('longitude_acidente', models.TextField(max_length=255)),
                ('hora_acidente', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Fazendo'), ('done', 'Feito')], max_length=5),
        ),
    ]
