# Generated by Django 4.1.8 on 2023-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_acidentes_rr_alter_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDeAtendimentoSistematizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_ou_vtr', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Acidentes_RR',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
